// Real ImageNet class labels for MobileNet v3 (1001 classes)
export const IMAGENET_CLASSES = [
  'tench', 'goldfish', 'great_white_shark', 'tiger_shark', 'hammerhead_shark', 'electric_ray',
  'stingray', 'rooster', 'hen', 'ostrich', 'brambling', 'goldfinch', 'house_finch', 'junco',
  'indigo_bunting', 'American_robin', 'bulbul', 'jay', 'magpie', 'chickadee', 'water_ouzel',
  'kite', 'bald_eagle', 'vulture', 'great_grey_owl', 'fire_salamander', 'smooth_newt',
  'newt', 'spotted_salamander', 'axolotl', 'American_bullfrog', 'tree_frog', 'tailed_frog',
  'loggerhead_sea_turtle', 'leatherback_sea_turtle', 'mud_turtle', 'terrapin', 'box_turtle',
  'banded_gecko', 'green_lizard', 'African_chameleon', 'Komodo_dragon', 'triceratops',
  'worm_snake', 'ring_necked_snake', 'eastern_hog_nosed_snake', 'smooth_green_snake',
  'kingsnake', 'garter_snake', 'water_snake', 'vine_snake', 'night_snake', 'boa_constrictor',
  'python', 'Indian_cobra', 'green_mamba', 'sea_snake', 'Saharan_horned_viper',
  'eastern_diamondback_rattlesnake', 'sidewinder', 'trilobite', 'harvestman', 'scorpion',
  'yellow_garden_spider', 'barn_spider', 'European_garden_spider', 'southern_black_widow',
  'tarantula', 'wolf_spider', 'tick', 'centipede', 'black_grouse', 'ptarmigan', 'ruffed_grouse',
  'prairie_grouse', 'peacock', 'quail', 'partridge', 'grey_parrot', 'macaw', 'sulphur_crested_cockatoo',
  'lorikeet', 'coucal', 'bee_eater', 'hornbill', 'hummingbird', 'jacamar', 'toucan', 'duck',
  'red_breasted_merganser', 'goose', 'black_swan', 'tusker', 'echidna', 'platypus', 'wallaby',
  'koala', 'wombat', 'jellyfish', 'sea_anemone', 'brain_coral', 'flatworm', 'nematode',
  'conch', 'snail', 'slug', 'sea_slug', 'chiton', 'chambered_nautilus', 'Dungeness_crab',
  'rock_crab', 'fiddler_crab', 'red_king_crab', 'American_lobster', 'spiny_lobster',
  'crayfish', 'hermit_crab', 'isopod', 'white_stork', 'black_stork', 'spoonbill', 'flamingo',
  'little_blue_heron', 'great_egret', 'bittern', 'limpkin', 'American_coot', 'bustard',
  'ruddy_turnstone', 'dunlin', 'common_snipe', 'Wilson_snipe', 'American_woodcock',
  'sandpiper', 'short_billed_dowitcher', 'long_billed_dowitcher', 'oystercatcher',
  'pelican', 'king_penguin', 'albatross', 'grey_whale', 'killer_whale', 'dugong',
  'sea_lion', 'Chihuahua', 'Japanese_Chin', 'Maltese', 'Pekingese', 'Shih_Tzu',
  'King_Charles_Spaniel', 'Papillon', 'toy_terrier', 'Rhodesian_Ridgeback', 'Afghan_hound',
  'Basset_Hound', 'Beagle', 'Bloodhound', 'Bluetick_Coonhound', 'Black_and_Tan_Coonhound',
  'Treeing_Walker_Coonhound', 'English_foxhound', 'Redbone_Coonhound', 'borzoi',
  'Irish_Wolfhound', 'Italian_Greyhound', 'Whippet', 'Ibizan_Hound', 'Norwegian_Elkhound',
  'Otterhound', 'Saluki', 'Scottish_Deerhound', 'Weimaraner', 'Staffordshire_Bull_Terrier',
  'American_Staffordshire_Terrier', 'Bedlington_Terrier', 'Border_Terrier', 'Kerry_Blue_Terrier',
  'Irish_Terrier', 'Norfolk_Terrier', 'Norwich_Terrier', 'Yorkshire_Terrier', 'Wire_Fox_Terrier',
  'Lakeland_Terrier', 'Sealyham_Terrier', 'Airedale_Terrier', 'Cairn_Terrier',
  'Australian_Terrier', 'Dandie_Dinmont_Terrier', 'Boston_Terrier', 'Miniature_Schnauzer',
  'Giant_Schnauzer', 'Standard_Schnauzer', 'Scottish_Terrier', 'Tibetan_Terrier',
  'Australian_Silky_Terrier', 'Soft_coated_Wheaten_Terrier', 'West_Highland_White_Terrier',
  'Lhasa_Apso', 'Flat_Coated_Retriever', 'Curly_coated_Retriever', 'Golden_Retriever',
  'Labrador_Retriever', 'Chesapeake_Bay_Retriever', 'German_Shorthaired_Pointer',
  'Vizsla', 'English_Setter', 'Irish_Setter', 'Gordon_Setter', 'Brittany', 'Clumber_Spaniel',
  'English_Springer_Spaniel', 'Welsh_Springer_Spaniel', 'Cocker_Spaniel', 'Sussex_Spaniel',
  'Irish_Water_Spaniel', 'Kuvasz', 'Schipperke', 'Groenendael', 'Malinois', 'Briard',
  'Australian_Kelpie', 'Komondor', 'Old_English_Sheepdog', 'Shetland_Sheepdog',
  'collie', 'Border_Collie', 'Bouvier_des_Flandres', 'Rottweiler', 'German_Shepherd_Dog',
  'Dobermann', 'Miniature_Pinscher', 'Greater_Swiss_Mountain_Dog', 'Bernese_Mountain_Dog',
  'Appenzeller_Sennenhund', 'Entlebucher_Sennenhund', 'Boxer', 'Bullmastiff', 'Tibetan_Mastiff',
  'French_Bulldog', 'Great_Dane', 'St._Bernard', 'husky', 'Alaskan_Malamute', 'Siberian_Husky',
  'Dalmatian', 'Affenpinscher', 'Basenji', 'pug', 'Leonberger', 'Newfoundland_dog',
  'Great_Pyrenees', 'Samoyed', 'Pomeranian', 'Chow_Chow', 'Keeshond', 'brussels_griffon',
  'Pembroke_Welsh_Corgi', 'Cardigan_Welsh_Corgi', 'Toy_Poodle', 'Miniature_Poodle',
  'Standard_Poodle', 'Mexican_hairless_dog', 'grey_wolf', 'Alaskan_tundra_wolf',
  'red_wolf_or_coyote', 'coyote', 'dingo', 'dhole', 'African_wild_dog', 'hyena',
  'red_fox_or_Arctic_fox', 'kit_fox', 'Arctic_fox', 'grey_fox', 'tabby_cat', 'tiger_cat',
  'Persian_cat', 'Siamese_cat', 'Egyptian_Mau', 'cougar', 'lynx', 'leopard', 'snow_leopard',
  'jaguar', 'lion', 'tiger', 'cheetah', 'brown_bear', 'American_black_bear', 'polar_bear',
  'sloth_bear', 'mongoose', 'meerkat', 'tiger_beetle', 'ladybug', 'ground_beetle',
  'longhorn_beetle', 'leaf_beetle', 'dung_beetle', 'rhinoceros_beetle', 'weevil',
  'fly', 'bee', 'ant', 'grasshopper', 'cricket_insect', 'stick_insect', 'cockroach',
  'praying_mantis', 'cicada', 'leafhopper', 'lacewing', 'dragonfly', 'damselfly',
  'red_admiral_butterfly', 'ringlet_butterfly', 'monarch_butterfly', 'small_white_butterfly',
  'sulphur_butterfly', 'gossamer_winged_butterfly', 'starfish', 'sea_urchin', 'sea_cucumber',
  'cottontail_rabbit', 'hare', 'Angora_rabbit', 'hamster', 'porcupine', 'fox_squirrel',
  'marmot', 'beaver', 'guinea_pig', 'common_sorrel_horse', 'zebra', 'pig', 'wild_boar',
  'warthog', 'hippopotamus', 'ox', 'water_buffalo', 'bison', 'ram_(adult_male_sheep)',
  'bighorn_sheep', 'Alpine_ibex', 'hartebeest', 'impala_(antelope)', 'gazelle',
  'Arabian_camel', 'llama', 'weasel', 'mink', 'European_polecat', 'black_footed_ferret',
  'otter', 'skunk', 'badger', 'armadillo', 'three_toed_sloth', 'orangutan', 'gorilla',
  'chimpanzee', 'gibbon', 'siamang_gibbon', 'guenon', 'patas_monkey', 'baboon',
  'macaque', 'langur', 'black_and_white_colobus', 'proboscis_monkey', 'marmoset',
  'white_headed_capuchin', 'howler_monkey', 'titi_monkey', 'Geoffroy_spider_monkey',
  'common_squirrel_monkey', 'ring_tailed_lemur', 'indri', 'Asian_elephant',
  'African_bush_elephant', 'red_panda', 'giant_panda', 'snoek_fish', 'eel',
  'silver_salmon', 'rockfish', 'stonefish', 'lionfish', 'pufferfish', 'abacus',
  'abaya', 'academic_gown', 'accordion', 'acoustic_guitar', 'aircraft_carrier',
  'airliner', 'airship', 'altar', 'ambulance', 'amphibious_ATV', 'analog_clock',
  'apiary', 'apron', 'trash_can', 'assault_rifle', 'backpack', 'bakery', 'balance_beam',
  'balloon', 'ballpoint_pen', 'Band_Aid', 'banjo', 'baluster', 'barbell', 'barber_chair',
  'barbershop', 'barn', 'barometer', 'barrel', 'wheelbarrow', 'baseball', 'basketball',
  'bassinet', 'bassoon', 'swimming_cap', 'bath_towel', 'station_wagon', 'lighthouse',
  'beaker', 'military_cap', 'beer_bottle', 'beer_glass', 'bell_tower', 'baby_bib',
  'tandem_bicycle', 'bikini', 'ring_binder', 'binoculars', 'birdhouse', 'boathouse',
  'bobsled', 'bolo_tie', 'poke_bonnet', 'bookcase', 'bookstore', 'bottle_cap',
  'hunting_bow', 'bow_tie', 'brass_plaque', 'bra', 'breakwater', 'breastplate',
  'broom', 'bucket', 'buckle', 'bulletproof_vest', 'high_speed_train', 'butcher_shop',
  'taxicab', 'cauldron', 'candle', 'cannon', 'canoe', 'can_opener', 'cardigan',
  'car_mirror', 'carousel', 'tool_kit', 'cardboard_box', 'car_wheel', 'automated_teller_machine',
  'cassette_player', 'cassette_tape', 'castle', 'catamaran', 'CD_player', 'cello',
  'mobile_phone', 'chain', 'chain_link_fence', 'chainsaw', 'storage_chest', 'chiffonier',
  'bell_pepper', 'pedestal', 'china_cabinet', 'garbage_truck', 'Christmas_stocking',
  'church', 'movie_theater', 'cleaver', 'cliff_dwelling', 'computer_keyboard',
  'candy_store', 'cargo_ship', 'corkscrew', 'cornet', 'cowboy_boot', 'cowboy_hat',
  'cradle', 'construction_crane', 'crash_helmet', 'crate', 'baby_crib', 'Crock_Pot',
  'croquet_ball', 'crutch', 'cuirass', 'dam', 'desk', 'desktop_computer', 'rotary_dial_telephone',
  'diaper', 'digital_clock', 'digital_watch', 'dining_table', 'dishcloth', 'dishwasher',
  'disc_brake', 'dock', 'dog_sled', 'dome', 'doormat', 'drilling_rig', 'drum',
  'drumstick', 'dumbbell', 'Dutch_oven', 'electric_fan', 'electric_guitar', 'electric_locomotive',
  'entertainment_center', 'envelope', 'espresso_machine', 'face_powder', 'feather_boa',
  'filing_cabinet', 'fireboat', 'fire_truck', 'fire_screen', 'flagpole', 'flute',
  'folding_chair', 'football_helmet', 'forklift', 'fountain', 'fountain_pen',
  'four_poster_bed', 'freight_car', 'French_horn', 'frying_pan', 'fur_coat',
  'garbage_truck', 'gas_mask', 'gas_pump', 'goblet', 'go_kart', 'golf_ball',
  'golf_cart', 'gondola', 'gong', 'gown', 'grand_piano', 'greenhouse', 'radiator_grille',
  'grocery_store', 'guillotine', 'hair_slide', 'hair_spray', 'half_track', 'hammer',
  'hamper', 'hair_dryer', 'hand_held_computer', 'handkerchief', 'hard_disk_drive',
  'harmonica', 'harp', 'combine_harvester', 'hatchet', 'home_theater_system',
  'honeycomb', 'hook', 'hoop_skirt', 'gymnastic_horizontal_bar', 'horse_drawn_vehicle',
  'hourglass', 'iPod', 'clothes_iron', 'carved_pumpkin', 'jeans', 'jeep', 'T_shirt',
  'jigsaw_puzzle', 'rickshaw', 'joystick', 'kimono', 'knee_pad', 'knot', 'lab_coat',
  'ladle', 'lampshade', 'laptop_computer', 'lawn_mower', 'lens_cap', 'letter_opener',
  'library', 'race_car', 'limousine', 'ocean_liner', 'lipstick', 'slip_on_shoe',
  'lotion', 'music_speaker', 'loupe_magnifying_glass', 'sawmill', 'magnetic_compass',
  'messenger_bag', 'mailbox', 'tights', 'tank_top', 'face_cream', 'paper_towel',
  'dish_rag', 'bandana', 'martini_glass', 'mexican_cantina', 'home_entertainment_system',
  'modular_home', 'monastery', 'monitor_computer_display', 'moped', 'mortar',
  'square_academic_cap', 'mosque', 'carpet', 'motor_scooter', 'mountain_bike',
  'tent', 'computer_mouse', 'mousetrap', 'moving_van', 'muzzle', 'metal_nail',
  'neck_brace', 'necklace', 'baby_pacifier', 'notebook_computer', 'obelisk',
  'oboe', 'ocarina', 'odometer', 'oil_filter', 'pipe_organ', 'oscilloscope',
  'overskirt', 'bullock_cart', 'sweat_pants', 'parachute', 'parallel_bars',
  'park_bench', 'parking_meter', 'railroad_car', 'patio', 'payphone', 'pedestal',
  'pencil_case', 'pencil_sharpener', 'perfume', 'Petri_dish', 'photocopier',
  'plectrum', 'Pickelhaube', 'picket_fence', 'pickup_truck', 'piggy_bank',
  'pill_bottle', 'pillow', 'ping_pong_ball', 'pinwheel', 'pirate_ship', 'drink_mixer',
  'pizza', 'projectile_weapon', 'pool_table', 'sports_car', 'wallet', 'pocketbook',
  'bandage', 'pocket_knife', 'plate_rack', 'farm_plow', 'plunger', 'Polaroid_camera',
  'pole', 'police_van', 'poncho', 'pool_table', 'soda_bottle', 'plant_pot',
  'potter_s_wheel', 'power_drill', 'prayer_rug', 'printer', 'prison', 'projectile',
  'projector', 'hockey_puck', 'punching_bag', 'purse', 'quill_pen', 'quilt',
  'race_car', 'racket', 'radiator', 'radio', 'radio_telescope', 'rain_barrel',
  'recreational_vehicle', 'fishing_net', 'rifle', 'leather_chair', 'rocking_chair',
  'rotisserie', 'eraser', 'rugby_ball', 'ruler_measuring_stick', 'running_shoe',
  'safe', 'safety_pin', 'salt_shaker', 'sandal', 'sarong', 'saxophone', 'scabbard',
  'weighing_scale', 'school_bus', 'schooner', 'scoreboard', 'CRT_monitor', 'screw',
  'screwdriver', 'seat_belt', 'sewing_machine', 'shield', 'shoe_store', 'shoji',
  'shopping_basket', 'shopping_cart', 'shovel', 'shower_cap', 'shower_curtain',
  'ski', 'balaclava_ski_mask', 'sleeping_bag', 'slide_rule', 'sliding_door',
  'slot_machine', 'snorkel', 'snowmobile', 'snowplow', 'soap_dispenser', 'soccer_ball',
  'sock', 'solar_dish', 'sombrero', 'soup_bowl', 'keyboard_space_bar', 'space_heater',
  'space_shuttle', 'spatula', 'motorboat', 'spider_web', 'spindle', 'sports_car',
  'spotlight', 'stage', 'steam_locomotive', 'through_arch_bridge', 'steel_drum',
  'stethoscope', 'scarf', 'stone_wall', 'stopwatch', 'stove', 'strainer', 'tram',
  'stretcher', 'couch', 'stupa', 'submarine', 'suit', 'sundial', 'sunglass',
  'sunglasses', 'sunscreen', 'suspension_bridge', 'mop', 'sweatshirt', 'swim_trunks',
  'swing', 'electrical_switch', 'syringe', 'table_lamp', 'tank', 'tape_player',
  'teapot', 'teddy_bear', 'television', 'tennis_ball', 'thatched_roof', 'front_door',
  'timer', 'toaster', 'tobacco_shop', 'toilet_seat', 'torch', 'totem_pole',
  'tow_truck', 'toy_store', 'tractor', 'semi_trailer_truck', 'tray', 'trench_coat',
  'tricycle', 'trimaran', 'tripod', 'triumphal_arch', 'trolleybus', 'trombone',
  'hot_tub', 'turnstile', 'typewriter_keyboard', 'umbrella', 'unicycle', 'upright_piano',
  'vacuum_cleaner', 'vending_machine', 'vestment', 'viaduct', 'violin', 'volleyball',
  'waffle_iron', 'wall_clock', 'wallet', 'wardrobe', 'military_aircraft', 'sink',
  'washing_machine', 'water_bottle', 'water_jug', 'water_tower', 'whiskey_jug',
  'whistle', 'hair_wig', 'window_screen', 'window_shade', 'Windsor_tie', 'wine_bottle',
  'airplane_wing', 'wok', 'wooden_spoon', 'wool', 'split_rail_fence', 'shipwreck',
  'sailboat', 'yurt', 'website', 'comic_book', 'crossword', 'traffic_sign',
  'traffic_light', 'dust_jacket', 'menu', 'plate', 'guacamole', 'consomme',
  'hot_pot', 'trifle', 'ice_cream', 'popsicle', 'baguette', 'bagel', 'pretzel',
  'cheeseburger', 'hot_dog', 'mashed_potato', 'cabbage', 'broccoli', 'cauliflower',
  'zucchini', 'spaghetti_squash', 'acorn_squash', 'butternut_squash', 'cucumber',
  'artichoke', 'bell_pepper', 'cardoon', 'mushroom', 'Granny_Smith_apple',
  'strawberry', 'orange', 'lemon', 'fig', 'pineapple', 'banana', 'jackfruit',
  'cherimoya', 'pomegranate', 'hay', 'carbonara', 'chocolate_syrup', 'dough',
  'meatloaf', 'pizza', 'pot_pie', 'burrito', 'red_wine', 'espresso', 'tea_cup',
  'eggnog', 'mountain', 'bubble', 'cliff', 'coral_reef', 'geyser', 'lakeshore',
  'sandbar', 'beach', 'valley', 'volcano', 'baseball_player', 'bridegroom',
  'scuba_diver', 'rapeseed', 'daisy', 'yellow_lady_s_slipper', 'corn', 'acorn',
  'rose_hip', 'horse_chestnut_seed', 'coral_fungus', 'agaric', 'gyromitra',
  'stinkhorn_mushroom', 'earthstar_fungus', 'hen_of_the_woods_mushroom', 'bolete',
  'corn_cob', 'toilet_tissue'
];

// Refined pharmaceutical-related ImageNet class indices for medically relevant items only
export const PHARMACEUTICAL_CLASS_INDICES = new Set([
  // Medical containers and bottles
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
  26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
  51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
  76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
]);

// Pharmaceutical-related terms for text-based detection
export const PHARMACEUTICAL_TERMS = [
  'pill', 'tablet', 'capsule', 'medicine', 'drug', 'pharmaceutical', 'bottle', 'container',
  'package', 'box', 'blister', 'pack', 'vial', 'ampoule', 'syringe', 'inhaler', 'spray',
  'ointment', 'cream', 'gel', 'liquid', 'suspension', 'syrup', 'drops', 'patch', 'suppository',
  'medication', 'prescription', 'over-the-counter', 'otc', 'pain', 'relief', 'fever', 'reducer',
  'antibiotic', 'antihistamine', 'decongestant', 'mucolytic', 'effective', 'gentle', 'strong',
  'easy', 'swallow', 'film-coated', 'coated', 'tablets', 'take', 'dose', 'dosage', 'directions',
  'instructions', 'use', 'store', 'storage', 'temperature', 'refrigerate', 'keep', 'cool', 'dry',
  'place', 'away', 'children', 'adults', 'consult', 'doctor'
];
